### ISSUE TITLE
Running Locally Without Docker

### ISSUE THREAD

**Issue by lowercase00** [charlesfranciscodev/vuejs-playground#1]
Hey mate, thanks a lot for this, I've been looking for some reference for quite a while now.
I was wondering if there's anyway to run the code without having to create the containers, just normal Flask app, but I couldn't make it work without the `run.py` to start the server. Anything I'm missing? Thanks!

**Comment by charlesfranciscodev** [comment]
I can show you how to run it locally without Docker.
The instructions below are for Linux (Debian/Ubuntu).
First, make sure you have Python 3 and pip installed.
After that, install Linux and Python dependencies:

```shell
sudo apt-get update
# For the next step, if you are using a Linux distro other than Debian/Ubuntu, please refer to the offical doc for bcrypt: https://github.com/pyca/bcrypt
sudo apt-get install -y build-essential libffi-dev python-dev 
cd vuejs-playground/server
pip3 install -r requirements.txt
```

Setup environment variables:

```shell
export FLASK_APP=project/__init__.py
export FLASK_ENV=development
export APP_SETTINGS=project.config.DevelopmentConfig
export DATABASE_URL=sqlite:///db_dev.db
```

Setup the database:
```shell
python3 manage.py recreate_db
python3 manage.py seed_db
```

If you check the Dockerfile for the server, the last instruction indicates the command to run the server:
```shell
python3 manage.py run -h 0.0.0.0
```

Now go to http://0.0.0.0:5000/


For Mac/Windows the setup might be different.
I would suggest using Docker for Mac/Windows, which allows you to run the app in a container, without having to install Linux on your computer or in a VM.

**Comment by charlesfranciscodev** [comment]
Just make sure you have the latest code.
If you cloned the repo with git you can do `git pull`.

**Comment by charlesfranciscodev** [comment]
Hey @lowercase00  did you try what I suggested?

**Comment by charlesfranciscodev** [comment]
Closing this issue. Please see my first comment for possible solutions.
